name: build

on: [push, pull_request]

jobs:
  ubuntu-2004:

    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: build_and_test
      run: ./build_and_test_multi.sh clean

  ubuntu-2204:

    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: build_and_test
      run: ./build_and_test_multi.sh clean

